POST http://localhost:3001/students
Content-Type: application/json

{
    "student": {
        "firstName": "Student 12",
        "lastName": "Last Name 12",
        "email": "student12@1.com",
        "password": "Password12?"
    },
    "courses": [1, 2]
}