GET http://localhost:3001/videos/student/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InN0dWRlbnQxMkAxLmNvbSIsImlkIjo1MTU0LCJyb2xlIjoic3R1ZGVudCIsImlhdCI6MTczMjMwMjYyMSwiZXhwIjoxNzMyNDc1NDIxfQ.zyq0vtjwqGkQ3z7M31c6kZd2nbeAXbXodvFO_9X-vFs

