GET http://localhost:3001/videos/admin/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkbWluQGFkbWluLmNvbSIsImlkIjo1NjE1LCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3MzIzNTQ3MTksImV4cCI6MTczMjUyNzUxOX0.426tFs2KtsWmYmfUJB9CNy-X18WSDo51lLLZH1VuTe4

